name: Build/release
on: push
jobs:
  release:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: "macOS-latest",   arch: "x64",    artifact_prefix: "macos"   }
          - { os: "windows-latest", arch: "x64",    artifact_prefix: "windows" }
          - { os: "ubuntu-latest",  arch: "x64",    artifact_prefix: "linux"   }
          - { os: "ubuntu-latest",  arch: "arm64", artifact_prefix: "arm"     }
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          args: --${{ matrix.job.arch }}
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
